source "https://rubygems.org"
# Run with
#   bundle exec jekyll serve (--port 4001)
#
# we use GitHub Pages
# gem "jekyll", "~> 4.0.1"
# To upgrade, run `bundle update github-pages`.
gem "github-pages", group: :jekyll_plugins
# PLUGINS
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
  gem "jekyll-relative-links"
end

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
install_if -> { RUBY_PLATFORM =~ %r!mingw|mswin|java! } do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :install_if => Gem.win_platform?

